// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Paranoid.

//! Sparse binary Merkle tree over Poseidon2b-compressed 32-byte digests.
//!
//! Implements the state tree and nullifier tree from CRYPTO.md §6:
//!
//! - Binary, fixed depth (DEPTH = 32 for chain-level trees; generic here).
//! - Inner node rule: [`native::compress`] (two-permutation sponge with
//!   `COMPRESS` IV, §5.1).
//! - Leaf rule: the leaf payload is a 32-byte digest passed in directly.
//!   Callers produce payloads with `hash_leaf` / `hash_commitment` /
//!   `hash_nullifier` depending on the tree.
//! - Empty subtrees use precomputed zero roots `Z[0..=DEPTH]` with
//!   `Z[0] = hash_leaf(&[])` and `Z[k] = compress(Z[k-1], Z[k-1])`.
//!
//! This is a *sparse* representation — only non-zero leaves are stored in
//! a `BTreeMap` keyed by leaf index. Inclusion / non-inclusion proofs are
//! generated by walking the sparse structure and substituting precomputed
//! zero-subtree roots for absent siblings, so a depth-32 tree with a few
//! thousand non-empty leaves costs O(depth) per update and O(depth) memory
//! per proof.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use noid_core::Block128;

use crate::native::compress;
use crate::primitives::hash_leaf;

/// A 32-byte digest; same convention as the rest of the crate.
pub type Digest = [u8; 32];

/// Depth used by the on-chain state and nullifier trees. CRYPTO.md §6.1.
pub const CHAIN_TREE_DEPTH: usize = 32;

/// Precomputed zero-subtree roots for `k` in `0..=64`.
///
/// `Z[0] = hash_leaf(&[])`
/// `Z[k] = compress(Z[k-1], Z[k-1])`
///
/// Computed once on first access. We materialize 65 entries so any tree
/// depth up to 64 can index `Z[DEPTH]` directly; depth-32 trees use
/// `Z[0..=32]`.
fn zero_roots() -> &'static [Digest; 65] {
    static ROOTS: OnceLock<[Digest; 65]> = OnceLock::new();
    ROOTS.get_or_init(|| {
        let mut z: [Digest; 65] = [[0u8; 32]; 65];
        z[0] = hash_leaf(&[] as &[Block128]);
        for k in 1..65 {
            z[k] = compress(&z[k - 1], &z[k - 1]);
        }
        z
    })
}

/// Precomputed `Z[k]` zero-subtree root at height `k`.
#[inline]
pub fn zero_root(height: usize) -> Digest {
    zero_roots()[height]
}

/// Root of a fully-empty sparse tree of a given depth.
#[inline]
pub fn empty_root(depth: usize) -> Digest {
    zero_root(depth)
}

/// An inclusion (or non-inclusion) proof: the sibling digest at every
/// level from the leaf up to (but not including) the root.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MerkleProof {
    pub depth: usize,
    pub index: u64,
    pub leaf: Digest,
    pub siblings: Vec<Digest>,
}

impl MerkleProof {
    /// Re-derive the root from `leaf`, `index`, and `siblings`. Callers
    /// pass the expected root and compare.
    pub fn compute_root(&self) -> Digest {
        assert_eq!(self.siblings.len(), self.depth, "proof depth mismatch");
        let mut cur = self.leaf;
        let mut idx = self.index;
        for sib in &self.siblings {
            let bit = idx & 1;
            cur = if bit == 0 {
                compress(&cur, sib)
            } else {
                compress(sib, &cur)
            };
            idx >>= 1;
        }
        cur
    }

    /// Verify the proof against an expected root.
    #[inline]
    pub fn verify(&self, expected_root: &Digest) -> bool {
        &self.compute_root() == expected_root
    }
}

/// Sparse binary Merkle tree of fixed `depth`. Indices run `0..2^depth`.
///
/// Uses a `BTreeMap<u64, Digest>` for non-zero leaves and recomputes the
/// root lazily from the sparse set of populated leaves on each `root()`
/// call. Designed for workloads where updates are clustered and the
/// population is always « 2^depth (e.g. a nullifier tree).
#[derive(Debug, Clone)]
pub struct SparseMerkleTree {
    depth: usize,
    leaves: BTreeMap<u64, Digest>,
}

impl SparseMerkleTree {
    /// Create an empty tree of the given depth. `depth` must be ≤ 64.
    pub fn new(depth: usize) -> Self {
        assert!(depth <= 64, "depth > 64 unsupported");
        Self {
            depth,
            leaves: BTreeMap::new(),
        }
    }

    /// Depth of the tree (number of levels from leaves to root).
    #[inline]
    pub fn depth(&self) -> usize {
        self.depth
    }

    /// Maximum leaf index + 1. For `depth == 64` this overflows — callers
    /// at that depth must index with `u64` modular arithmetic.
    #[inline]
    pub fn capacity(&self) -> u128 {
        1u128 << self.depth
    }

    /// Number of non-zero leaves currently stored.
    #[inline]
    pub fn len(&self) -> usize {
        self.leaves.len()
    }

    #[inline]
    pub fn is_empty(&self) -> bool {
        self.leaves.is_empty()
    }

    /// Current leaf digest at `index` (returns `Z[0]` for empty slots).
    pub fn get(&self, index: u64) -> Digest {
        self.assert_in_range(index);
        match self.leaves.get(&index) {
            Some(d) => *d,
            None => zero_root(0),
        }
    }

    /// Insert or overwrite the leaf at `index`. A `ZERO_DIGEST` leaf is
    /// treated as "present and explicitly zero" — the caller asked for it
    /// to be materialized. Use [`clear`] to restore the sparse default.
    pub fn insert(&mut self, index: u64, leaf: Digest) {
        self.assert_in_range(index);
        self.leaves.insert(index, leaf);
    }

    /// Remove an explicit leaf, restoring the sparse default (`Z[0]`).
    pub fn clear(&mut self, index: u64) {
        self.leaves.remove(&index);
    }

    /// Current root of the tree.
    pub fn root(&self) -> Digest {
        if self.leaves.is_empty() {
            return zero_root(self.depth);
        }
        self.root_recursive(0, self.depth)
    }

    /// Inclusion or non-inclusion proof for `index`. The proof verifies
    /// against [`SparseMerkleTree::root`] regardless of whether the leaf
    /// is materialized — an absent leaf carries `Z[0]` and proves
    /// non-inclusion.
    pub fn proof(&self, index: u64) -> MerkleProof {
        self.assert_in_range(index);
        let leaf = self.get(index);
        let mut siblings = Vec::with_capacity(self.depth);
        self.collect_siblings(index, 0, self.depth, &mut siblings);
        MerkleProof {
            depth: self.depth,
            index,
            leaf,
            siblings,
        }
    }

    // --- internal helpers -------------------------------------------------

    fn assert_in_range(&self, index: u64) {
        if self.depth < 64 {
            let cap = 1u64 << self.depth;
            assert!(
                index < cap,
                "leaf index {} out of range (depth {})",
                index,
                self.depth
            );
        }
    }

    /// Recursively compute the root of the subtree rooted at `(prefix,
    /// level)`, where `level` is the height remaining (leaves at
    /// `level == 0`, root at `level == self.depth`).
    fn root_recursive(&self, prefix: u64, level: usize) -> Digest {
        // Find leaves whose index starts with `prefix` in its top
        // `self.depth - level` bits.
        let shift = level;
        let lo = prefix << shift;
        let hi_excl = lo.saturating_add(1u64 << shift);

        // Fast path: no populated leaves in this subtree.
        if self.subtree_is_empty(lo, hi_excl) {
            return zero_root(level);
        }

        if level == 0 {
            // Single leaf; must exist because the range was non-empty.
            return *self.leaves.get(&lo).unwrap_or(&zero_root(0));
        }

        let left = self.root_recursive(prefix << 1, level - 1);
        let right = self.root_recursive((prefix << 1) | 1, level - 1);
        compress(&left, &right)
    }

    /// Walk from root to leaf collecting the sibling of every step into
    /// `siblings` (leaf-first order).
    fn collect_siblings(&self, index: u64, prefix: u64, level: usize, out: &mut Vec<Digest>) {
        if level == 0 {
            return;
        }
        // The child we descend into has one more bit of prefix. The
        // sibling is the *other* child of the current node.
        let bit_pos = level - 1;
        let bit = (index >> bit_pos) & 1;
        let sibling_prefix = (prefix << 1) | (1 - bit);
        let child_prefix = (prefix << 1) | bit;

        // Push sibling subtree root first at the *top*, then recurse;
        // because proofs are leaf-first, reverse at the end.
        let sib_root = self.root_recursive(sibling_prefix, level - 1);
        self.collect_siblings(index, child_prefix, level - 1, out);
        out.push(sib_root);
    }

    /// Does the sparse leaf map contain any entry in `[lo, hi_excl)`?
    fn subtree_is_empty(&self, lo: u64, hi_excl: u64) -> bool {
        // BTreeMap range is half-open.
        self.leaves.range(lo..hi_excl).next().is_none()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zero_roots_are_layered_compressions_of_leaf_empty() {
        let z0 = zero_root(0);
        assert_eq!(z0, hash_leaf(&[] as &[Block128]));
        let z1 = zero_root(1);
        assert_eq!(z1, compress(&z0, &z0));
        let z2 = zero_root(2);
        assert_eq!(z2, compress(&z1, &z1));
    }

    #[test]
    fn empty_tree_root_matches_zero_root() {
        for depth in [0usize, 1, 4, 8, 16, 32] {
            let t = SparseMerkleTree::new(depth);
            assert_eq!(t.root(), zero_root(depth));
        }
    }

    #[test]
    fn single_leaf_inclusion_verifies() {
        let mut t = SparseMerkleTree::new(8);
        let leaf = [0xABu8; 32];
        t.insert(5, leaf);
        let p = t.proof(5);
        assert_eq!(p.leaf, leaf);
        assert!(p.verify(&t.root()));
    }

    #[test]
    fn non_inclusion_verifies_against_root() {
        let mut t = SparseMerkleTree::new(8);
        t.insert(5, [0xABu8; 32]);
        // Index 6 is empty; proof must verify and leaf must be Z[0].
        let p = t.proof(6);
        assert_eq!(p.leaf, zero_root(0));
        assert!(p.verify(&t.root()));
    }

    #[test]
    fn multiple_leaves_all_verify() {
        let mut t = SparseMerkleTree::new(16);
        let entries = [
            (0u64, [1u8; 32]),
            (42, [2u8; 32]),
            (100, [3u8; 32]),
            (0xFFFF, [4u8; 32]),
        ];
        for (i, d) in &entries {
            t.insert(*i, *d);
        }
        let root = t.root();
        for (i, d) in &entries {
            let p = t.proof(*i);
            assert_eq!(p.leaf, *d);
            assert!(p.verify(&root));
        }
        // Also check non-inclusion at a random empty slot.
        let p = t.proof(777);
        assert_eq!(p.leaf, zero_root(0));
        assert!(p.verify(&root));
    }

    #[test]
    fn insert_then_clear_restores_empty_root() {
        let mut t = SparseMerkleTree::new(8);
        let original = t.root();
        t.insert(3, [9u8; 32]);
        assert_ne!(t.root(), original);
        t.clear(3);
        assert_eq!(t.root(), original);
    }

    #[test]
    fn update_changes_root_and_proof() {
        let mut t = SparseMerkleTree::new(8);
        t.insert(7, [1u8; 32]);
        let r1 = t.root();
        t.insert(7, [2u8; 32]);
        let r2 = t.root();
        assert_ne!(r1, r2);

        let p = t.proof(7);
        assert_eq!(p.leaf, [2u8; 32]);
        assert!(p.verify(&r2));
    }

    #[test]
    fn depth32_chain_tree_works() {
        let mut t = SparseMerkleTree::new(CHAIN_TREE_DEPTH);
        let i = 0x1234_5678u64;
        t.insert(i, [7u8; 32]);
        let p = t.proof(i);
        assert_eq!(p.siblings.len(), CHAIN_TREE_DEPTH);
        assert!(p.verify(&t.root()));
    }
}
