[workspace]
members = [
    "bench_prover",
    "noid_core",
    "noid_fri",
    "noid_poseidon2b",
    "noid_tx",
    "noid_chain",
    "noid_air",
    "noid_stark",
    "noid_ivc",
    "noid_binius",
    "noid_gkr",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
