[package]
name = "noid_miner"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
noid_chain    = { path = "../noid_chain" }
noid_poseidon2b = { path = "../noid_poseidon2b" }
noid_block    = { path = "../noid_block" }
noid_gkr      = { path = "../noid_gkr" }
noid_air      = { path = "../noid_air" }
noid_recursive = { path = "../noid_recursive" }
noid_tx       = { path = "../noid_tx" }
noid_stark    = { path = "../noid_stark" }
noid_mempool  = { path = "../noid_mempool" }
blake3        = "1"
hex           = "0.4"
rayon         = "1"
tokio         = { workspace = true }
tracing       = { workspace = true }
thiserror     = { workspace = true }
anyhow        = { workspace = true }
bincode       = "1"

[dev-dependencies]
bench_prover = { path = "../bench_prover" }
tempfile = "3"
