[package]
name = "noid_recursive"
version = "0.1.0"
edition = "2021"

[dependencies]
noid_core = { path = "../noid_core" }
noid_poseidon2b = { path = "../noid_poseidon2b" }
noid_chain = { path = "../noid_chain" }
noid_gkr = { path = "../noid_gkr" }
rayon = "1"
serde = { version = "1", features = ["derive"] }
bincode = "1"

[dev-dependencies]
noid_tx = { path = "../noid_tx" }
