[package]
name = "noid_block"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
noid_core       = { path = "../noid_core" }
noid_fri        = { path = "../noid_fri" }
noid_fri_binius = { path = "../noid_fri_binius" }
noid_poseidon2b = { path = "../noid_poseidon2b" }
noid_tx         = { path = "../noid_tx" }
noid_air        = { path = "../noid_air" }
noid_stark      = { path = "../noid_stark" }
noid_gkr        = { path = "../noid_gkr" }
noid_chain      = { path = "../noid_chain" }
rayon           = "1.10"
